version: '3'
services:

  caddy:
    build:
      context: ..
      dockerfile: docker/proxy/Dockerfile
    environment:
      TOB_API_URL: ${TOB_API_URL:-}
      WEB_BASE_HREF: ${WEB_BASE_HREF:-/}
      WEB_HOST_NAME: ${WEB_HOST_NAME:-0.0.0.0}
      WEB_HOST_PORT: ${WEB_HOST_PORT:-8080}
      WEB_HOST_TLS: ${WEB_HOST_TLS:-off}
      AGENT_HOST: ${AGENT_HOST:-agent}
      AGENT_PORT: ${AGENT_PORT:-8000}
      AGENT_USER: ${AGENT_USER}
      AGENT_PASSWORD: ${AGENT_PASSWORD}
    links:
      - gccorp-agent:agent
    networks:
      - vonx
    ports:
      - ${WEB_HTTP_PORT:-5000}:${WEB_HOST_PORT:-8080}
    volumes:
      - caddy-data:/root/.caddy
      - caddy-logs:/srv/logs

  gccorp-agent:
    build:
      context: ..
      dockerfile: docker/agent/Dockerfile
    environment:
      APPLICATION_URL: ${APPLICATION_URL:-http://localhost:5000}
      ENDPOINT_URL: ${ENDPOINT_URL:-http://localhost:5001}
      CONFIG_ROOT: ../config
      ENVIRONMENT: ${ENVIRONMENT:-default}
      ENABLE_GUNICORN: ${ENABLE_GUNICORN:-0}
      INDY_LEDGER_URL: ${LEDGER_URL:-http://localhost:9000}
      FORMS: ${FORMS:-}
      ISSUERS: ${ISSUERS:-}
      LOG_LEVEL: ${LOG_LEVEL:-}
      PYTHON_ENV: ${PYTHON_ENV:-development}
      TOB_API_URL: ${TOB_API_URL:-}
      TOB_APP_URL: ${TOB_APP_URL:-}
      WALLET_TYPE: ${WALLET_TYPE}
      POSTGRESQL_WALLET_HOST: ${POSTGRESQL_WALLET_HOST}
      POSTGRESQL_WALLET_PORT: ${POSTGRESQL_WALLET_PORT}
      POSTGRESQL_WALLET_USER: ${POSTGRESQL_USER}
      POSTGRESQL_WALLET_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRESQL_WALLET_ADMIN_PASSWORD: ${POSTGRESQL_ADMIN_PASSWORD}
      WALLET_ENCRYPTION_KEY: ${WALLET_ENCRYPTION_KEY}
      INDY_WALLET_SEED: ${INDY_WALLET_SEED:-}
      INDY_WALLET_DID: ${INDY_WALLET_DID}
    networks:
      - orgbook
      - vonx
    depends_on:
      - wallet-db
    volumes:
      - gccorp-agent-wallet:/home/indy/.indy_client/wallet

  wallet-db:
    image: registry.access.redhat.com/rhscl/postgresql-95-rhel7:9.5
    environment:
      - POSTGRESQL_USER=${POSTGRESQL_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_ADMIN_PASSWORD=${POSTGRESQL_ADMIN_PASSWORD}
    networks:
      - orgbook
    ports:
      - 5431:5432
    volumes:
      - wallet-db:/var/lib/pgsql/data

volumes:
  caddy-data:
  caddy-logs:
  gccorp-agent-wallet:
  wallet-db:

networks:
  vonx:
  orgbook:
    external:
      name: tob_tob
