issuers:
  GCCORP:
    path: /gccorp

forms:
  gccorp-incorp:
    path: /gccorp/registration
    type: issue-credential
    schema_name: registration.von.canada.ca
    page_title: Federal Corporation Registries
    title: Registration
    template: gccorp.index.html
    description: >
      Corporations Canada is the country’s federal corporate regulator. It administers the laws that allow Canadians to create and maintain a corporation under the federal laws governing corporations in Canada. Note that financial institutions are incorporated by the Office of the Superintendent of Financial Institutions.
    explanation: Use the form below to register a Federal corporation.

    js_includes:
      - src: js/gccorp.js

    fields:
      - name: entity_name
        label: Business Name
        type: text
        required: true

      - name: address
        label: Business Address
        type: address
        required: true

    mapping:
      attributes:
        - name: registration_id
          from: helper
          source: uuid

        - name: eneity_type
          from: literal
          source: null

        - name: effective_date
          from: helper
          source: now

        - name: entity_status
          from: literal
          source: null
